[package]
name = "js2wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
oxc = "0.5"

[lib]
name = "js2wasm"
path = "src/lib.rs"

[[bin]]
name = "js2wasm"
path = "src/main.rs"
